format_version: 10
pipelines:
  rollback-cache:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      fon:
        ignore_for_scheduling: true
        pipeline: fon
        stage: stage2-prod
    stages:
    - stage-rollback:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job-rollback:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - rollingback
                command: echo
                run_if: passed
